### ISSUE TITLE
broken installation

### ISSUE THREAD

**Issue by antonkulaga** [statgen/Rprs#16]
Your installation is broken. When I do:
```
devtools::install_github("statgen/Rprs")
```
I get:
```
  -- Installing: /tmp/Rtmpa4WBKD/Rbuild28e2c8dbbb2/Rprs/thirdParty/cget/cget/pkg/zstd/install/lib/libzstd.a
   Downloading http://zlib.net/zlib-1.2.11.tar.gz
   
   Download failed with error 404 for: //zlib.net/zlib-1.2.11.tar.gz
   Failed to build package statgen/savvy
   ERROR: configuration failed for package ‘Rprs’
─  removing ‘/tmp/Rtmpa4WBKD/Rinst28e2945c476/Rprs’
         -----------------------------------
   ERROR: package installation failed
The command '/bin/sh -c R -f /tmp/install.R' returned a non-zero code: 1

```

**Comment by antonkulaga** [comment]
it looks like a dependency hell with https://github.com/statgen/savvy
In my docker file ( https://github.com/dna-seq/containers/blob/main/prs/Dockerfile ) I am trying to switch to my work that uses latest version of savvy to overcome broken zlib download, however it seems like new version is not compatible with Prs

**Comment by jonathonl** [comment]
Please try the `fix/broken-zlib-url` branch of Rprs. I believe it can be done with `devtools::install_github("statgen/Rprs@fix/broken-zlib-url")`

**Comment by antonkulaga** [comment]
@jonathonl the fix works, thank you!
